server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
  zipkin:
    base-url: http://localhost:10020   #链路监控
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
fdfs:
  so-timeout: 1501 #读取时间
  connect-timeout: 601 #连接超时时间
  thumb-image:
    width: 60 #缩略图
    height: 60
  tracker-list: #tracker地址（远程虚拟机地址）
    - 192.168.56.80:22122