server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
  rabbitmq:
    host: 192.168.56.80
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEUYOU.ITEM.EXCHANGE  #默认的交换机
    publisher-confirms: true
mybatis:
  type-aliases-package: com.leyou.item.pojo
  mapper-locations: classpath:mappers/**.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15