server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
  rabbitmq:
    host: 192.168.56.80
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEUYOU.ITEM.EXCHANGE  #默认的交换机
    publisher-confirms: true
  zipkin:
    base-url: http://localhost:10020   #链路监控
  sleuth:
    sampler:
      probability: 1.0
mybatis:
  type-aliases-package: com.leyou.item.pojo
  mapper-locations: classpath:mappers/**.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15