server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.56.80
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAIrSADDEk7w017 # 你自己的accessKeyId
    accessKeySecret: 3VbBCdGJN2VUSAMNMj3yIlNg665JL0  # 你自己的AccessKeySecret
    signName: 徐皓 # 签名名称
    verifyCodeTemplate: SMS_139830104 # 模板名称