server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.56.80
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
ribbon:
  eager-load:
    enabled: true
leyou:
  jwt:
    pubKeyPath: C:\\tem\\rsa\\rsa.pub # 公钥地址
    cookieName: Ly_TOKEN