server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.56.80
  zipkin:
    base-url: http://localhost:10020   #链路监控
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ribbon:
  eager-load:
    enabled: true
leyou:
  jwt:
    pubKeyPath: C:\\tem\\rsa\\rsa.pub # 公钥地址
    cookieName: Ly_TOKEN